#!/bin/bash
#
set -x
VERSION=1.0
DIRNAME=`dirname $0`
CONFIG_FILE=${DIRNAME}/Setup.conf
FUNCTIONS_FILE=${DIRNAME}/functions.sh

if [ ! -f $CONFIG_FILE ] ; then
        echo "ERROR: Unable to read $CONFIG_FILE"
        exit 1
fi

. $CONFIG_FILE
. $FUNCTIONS_FILE

check_var

set -x

echo set hotname
hostname $LINUX_HOSTNAME
hostname > /etc/hostname

echo Setup Chrony time
DATE=`date +'%Y%m%d%H%M%S'`
cp /etc/chrony.conf /etc/chrony.conf_$DATE
cp ./chrony.conf /etc/chrony.conf
systemctl restart chronyd
chronyc sources
clean_and_exit "terminate" 0

echo check DNS entry for Linux NFS client
HOSTNAME=`hostname` 
nslookup $HOSTNAME
[ $? -ne 0 ] && clean_and_exit "Error no DNS entry for $HOSTNAME" 1

echo  Realm
realm discover -v dc1.demo.netapp.com
echo $PASSWD | realm join -U administrator dc1.demo.netapp.com
realm list

echo Check LDAP user exists
ldapsearch -LLL -H ldap://dc1.demo.netapp.com  -x -D "Administrator@demo.netapp.com" -b dc=demo,dc=netapp,dc=com -s sub "(uid=user1)" -w "$PASSWD"
ldapsearch -LLL -H ldap://dc1.demo.netapp.com  -x -D "Administrator@demo.netapp.com" -b dc=demo,dc=netapp,dc=com -s sub "(uid=user2)" -w "$PASSWD"
id user1@$DOMAIN
[ $? -ne 0 ] && clean_and_exit "Error user1 not in AD " 1
id user2@$DOMAIN
[ $? -ne 0 ] && clean_and_exit "Error user2 not in AD " 1

echo sssd Setup
cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf_$DATE
cp ./sssd.conf  /etc/sssd/sssd.conf
systemctl restart sssd
sss_cache -E

echo List cached Kerberos tickets
klist -k

echo Check Unix AD users
id user1
[ $? -ne 0 ] && clean_and_exit "Error user1 not in AD " 1
id user2
[ $? -ne 0 ] && clean_and_exit "Error user2 not in AD " 1


echo "Setup ONTAP NFSv4 Domain"
cp /etc/idmapd.conf /etc/idmapd.conf_$DATE
cp ./idmapd.conf /etc/idmapd.conf
nfsidmap -c
systemctl restart nfs-idmapd