#!/bin/bash
#
set -x
VERSION=1.0
DIRNAME=`dirname $0`
CONFIG_FILE=${DIRNAME}/Setup.conf
FUNCTIONS_FILE=${DIRNAME}/functions.sh

if [ ! -f $CONFIG_FILE ] ; then
        echo "ERROR: Unable to read $CONFIG_FILE"
        exit 1
fi

. $CONFIG_FILE
. $FUNCTIONS_FILE

check_var

set -x

echo Setup Chrony time
DATE=`date +'%Y%m%d%H%M%S'`
cp /etc/chrony.conf /etc/chrony.conf_$DATE
cp ./chrony.conf /etc/chrony.conf
systemctl restart chronyd
chronyc sources
clean_and_exit "terminate" 0

echo Check Realm
realm discover dc1.demo.netapp.com

echo Intall PowerShell
