#!/bin/bash
#
set -x
VERSION=1.0
DIRNAME=`dirname $0`
CONFIG_FILE=${DIRNAME}/Setup.conf
FUNCTIONS_FILE=${DIRNAME}/functions.sh

if [ ! -f $CONFIG_FILE ] ; then
        echo "ERROR: Unable to read $CONFIG_FILE"
        exit 1
fi

. $CONFIG_FILE
. $FUNCTIONS_FILE

check_var

set -x
DATE=`date +'%Y%m%d%H%M%S'`

# Check Connection
check_ssh_keyhost cluster1
sshpass -p $PASSWD ssh -l admin cluster1 version 

# Gets Free Data Aggregate
echo Check for data Aggregate on each clusters 
AGGR_DATA_CL1=`sshpass -p $PASSWD ssh -l admin cluster1 aggr show -root false |grep online |sort -k2 -u | tail -1 |awk '{print $1}'|tr -d '\r'`
[ -z "$AGGR_DATA_CL1" ] && clean_and_exit "ERROR: No Data Aggregate found in cluster1"

echo Setup LDAP
sshpass -p $PASSWD ssh -l admin cluster1 ldap client create -client-config ldapclient1 -ldap-servers ${LDAP_SERVER} -schema AD-IDMU -port 389 -query-timeout 3 -min-bind-level anonymous -base-dn "{$LDAP_BASE_DN}" -base-scope subtree -use-start-tls false -session-security none -referral-enabled false -ldaps-enabled false -bind-dn administrator@${DOMAIN}
sshpass -p $PASSWD ssh -l admin cluster1 ldap client show
sshpass -p $PASSWD ssh -l admin cluster1 ldap create -vserver $SVM1 -client-config ldapclient1 -skip-config-validation false
sshpass -p $PASSWD ssh -l admin cluster1 vserver services name-service ns-switch modify -vserver $SVM1 -database passwd -sources  files,ldap
sshpass -p $PASSWD ssh -l admin cluster1 vserver services name-service ns-switch modify -vserver $SVM1 -database group -sources  files,ldap
sshpass -p $PASSWD ssh -l admin cluster1 ns-switch show -vserver $SVM1 

# Check ONTAP Client LDAP Resolution Name"
sshpass -p $PASSWD ssh -l admin cluster1 "set advanced ; vserver services access-check authentication translate -node cluster1-01 -vserver $SVM1 -unix-user-name user1"
sshpass -p $PASSWD ssh -l admin cluster1 "set advanced ; vserver services access-check authentication translate -node cluster1-01 -vserver $SVM1 -unix-user-name user2"
sshpass -p $PASSWD ssh -l admin cluster1 "set advanced ; vserver services access-check authentication translate -node cluster1-01 -vserver $SVM1 -unix-user-name user3"

# Modift NFS Permitted Encyption 
# ASP sshpass -p $PASSWD ssh -l admin cluster1 vserver nfs modify -vserver $SVM1 -permitted-enc-types aes-*
sshpass -p $PASSWD ssh -l admin cluster1 vserver nfs show -vserver $SVM1 -fields permitted-enc-types

echo Setup SVM ONTAP kerberos
KDC_IP=`getent hosts demo.netapp.com |awk '{print $1}'`
sshpass -p $PASSWD ssh -l admin cluster1 kerberos realm create -vserver $SVM1 -realm ${DOMAIN^^} -kdc-vendor Microsoft -kdc-ip $KDC_IP -kdc-port 88 -clock-skew 5 -adminserver-ip $KDC_IP -adminserver-port 749 -passwordserver-ip $KDC_IP -passwordserver-port 464 -adserver-name dc1 -adserver-ip $KDC_IP
sshpass -p $PASSWD ssh -l admin cluster1 kerberos realm show 

echo Setup NFS Kerberose
echo "Kerberose SPN: nfs/${SVM1}@${DOMAIN^^}"
sshpass -p $PASSWD ssh -l admin cluster1 vserver nfs kerberos interface enable -vserver $SVM1 -lif $SVM1_LIF_NFS_KERBEROS -spn nfs/${SVM1}@${DOMAIN^^}
sshpass -p $PASSWD ssh -l admin cluster1 vserver nfs kerberos interface show -vserver $SVM1 
echo "Check KDC Service Principal NFS-SVM1 with PowerShell: Get-ADComputer -Properties KerberosEncryptionType,ServicePrincipalName NFS-SVM1"
getent hosts NFS-SVM1.DEMO.NETAPP.COM
[ $? -ne 0 ] && clean_and_exit "Error DNS entry NFS-SVM1 is missing" 1

Creaet a name-mapping krb-unix rule 
sshpass -p $PASSWD ssh -l admin cluster1 "vserver name-mapping create -vserver $SVM1 -direction krb-unix -position 1 -pattern (.+)\\\$@DEMO.NETAPP.COM -replacement root"
sshpass -p $PASSWD ssh -l admin cluster1 "vserver name-mapping show -vserver $SVM1 -direction krb-unix"
echo Check krb-unix mapping
sshpass -p $PASSWD ssh -l admin cluster1 "set advanced; vserver services access-check name-mapping show -node cluster1-01 -vserver $SVM1 -direction krb-unix -name RHEL1\$@DEMO.NETAPP.COM"

echo "Setup ONTAP NFSv4 Domain"
sshpass -p $PASSWD ssh -l admin cluster1 vserver nfs modify -v4-id-domain $DOMAIN -vserver $SVM1

echo Create NFS / CIFS Volume
sshpass -p $PASSWD ssh -l admin cluster1 vserver modify -vserver $SVM1 -aggr-list $AGGR_DATA_CL1 
sshpass -p $PASSWD ssh -l admin cluster1 volume create -vserver $SVM1 -volume volnfs1 -security-style unix -state online -aggregate $AGGR_DATA_CL1  -junction-path /volnfs1
sshpass -p $PASSWD ssh -l admin cluster1 volume create -vserver $SVM1 -volume volcifs1 -security-style ntfs -state online -aggregate $AGGR_DATA_CL1  -junction-path /volcifs1
sshpass -p $PASSWD ssh -l admin cluster1 vserver cifs share create -share-name volnfs1 -path /volnfs1
sshpass -p $PASSWD ssh -l admin cluster1 vserver cifs share create -share-name volcifs1 -path /volcifs1
sshpass -p $PASSWD ssh -l admin cluster1 vserver cifs share show 

echo Create Rules
sshpass -p $PASSWD ssh -l admin cluster1 export-policy create -policyname kerberos_default -vserver $SVM1 
sshpass -p $PASSWD ssh -l admin cluster1 export-policy rule create -vserver $SVM1 -policyname kerberos_default -clientmatch 0.0.0.0/0 -rorule krb5p -rwrule krb5p -allow-suid true -allow-dev true -protocol nfs3,nfs4,cifs -superuser krb5p
sshpass -p $PASSWD ssh -l admin cluster1 volume modify -volume volnfs1 -policy kerberos_default -vserver $SVM1
sshpass -p $PASSWD ssh -l admin cluster1 volume modify -volume volcifs1 -policy kerberos_default -vserver $SVM1

kinit user1@DEMO.NETAPP.COM
klist -kte
[ ! -d /volnfs1 ] && mkdir /volnfs1
[ ! -d /volcifs1 ] && mkdir /volcifs1
mount -t nfs -o vers=4.2,sec=krb5p svm1:/volcifs1 /volcifs1
mount -t nfs -o vers=4.2,sec=krb5p svm1:/volnfs1 /volnfs1
