#!/bin/bash
#
set -x
VERSION=1.0
DIRNAME=`dirname $0`
CONFIG_FILE=${DIRNAME}/Setup.conf
FUNCTIONS_FILE=${DIRNAME}/functions.sh

if [ ! -f $CONFIG_FILE ] ; then
        echo "ERROR: Unable to read $CONFIG_FILE"
        exit 1
fi

. $CONFIG_FILE
. $FUNCTIONS_FILE

check_var

set -x
DATE=`date +'%Y%m%d%H%M%S'`

# Check Connection
check_ssh_keyhost cluster1
sshpass -p $PASSWD ssh -l admin cluster1 version 

# Enable s3 protocol on LIF
sshpass -p $PASSWD ssh -l admin cluster1 "set advanced; network interface service-policy add-service -vserver svm1 -policy default-data-files -service data-s3-server"
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server create -vserver svm1 -object-store-server svm1 -is-http-enabled true -is-https-enabled false -listener-port 80 -secure-listener-port 443 -status-admin up
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server show -vserver svm1
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server user create -vserver svm1 -user user1
echo Copy the keys
echo ====================================================================
read
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server user create -vserver svm1 -user user2
echo Copy the keys
echo ====================================================================
read

sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server group create -vserver svm1 -name users  -users user1,user2 -policies FullAccess
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server bucket create -vserver svm1 -bucket volnfs1 -type nas -nas-path /volnfs1
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server bucket create -vserver svm1 -bucket volcif1 -type nas -nas-path /volcifs1
sshpass -p $PASSWD ssh -l admin cluster1 vserver object-store-server bucket create -vserver svm1 -bucket bucket1 -type s3 -size 10GB
