apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volcifs1 
  namespace: alpine
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: pv-volcifs1 
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volcifs1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 4Gi
  nfs:
    path: /volcifs1 
    server: 172.30.0.134
